name: Push and Deploy Serverless function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/yandex-serverless-action@v1
        with:
          token: ${{ secrets.TOKEN }}
          function_id: ${{ secrets.FUNCTION_ID }}
          runtime: 'python38'
          entrypoint: 'index.handler'
          environment: TG_TOKEN=${{ secrets.TG_TOKEN }}
          memory: '128'
          execution_timeout: '5'
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          source: '.'
          exclude: '.git/,.github/,/.gitignore,.README.md'